frontend/controllers/ExamController.php
<?php

namespace frontend\controllers;

use common\models\Exams;
use frontend\models\UserExam;
use Yii;
use yii\helpers\Json;
use yii\i18n\Formatter;


class ExamController extends \yii\web\Controller
{
        
    public function actionIndex()
    {
        $exams = Exams::find();
        $taken = UserExam::findAll(['user_id' => Yii::$app->user->getId()]);
        return $this->render('index', ['exams' => $exams, 'taken' => $taken]);
    }
    
    public function actionExam($id) {
        $model = new UserExam();
        $exam = Exams::findOne(['id' => $id]);
        $formate = new Formatter();
        $model->user_id = Yii::$app->user->getId();
        $model->exam_id = $id;
        if ($model->load(Yii::$app->request->post())){
            $mark = $this->getResult($model, $exam);
            return $this->render('result', ['mark' => $mark]);    
        } else {
        return $this->render('exam', ['exam' => $exam, 'model' => $model]);
        }
    
    }
    
    public function getResult ($model, $exam) {
        $formate = new Formatter();
        $model->end = (int)$formate->asTimestamp(date("Y-m-d H:i:s"));
        $mark = 0;
        $questions = 0;
        $teest = Json::decode($exam->getAttribute('exam'));
        foreach($model->getAttribute('answers') as $key => $test){
            if ($teest['exam']['question' . $key]['right'] == $test){
                $mark++;
            }
            $questions++;
        }
        $model->mark = $mark . '/' .$questions;
        $mark/$questions < 0.5 ? $model->failed = 1 : $model->failed = 0;
        $model->answers = Json::encode($model->answers);
        $model->save();
        return $mark;
    }

}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
//    NavBar::begin([
//        'brandLabel' => Yii::$app->name,
//        'brandUrl' => Yii::$app->homeUrl,
//        'options' => [
//            'class' => 'navbar-inverse navbar-fixed-top',
//        ],
//    ]);
    if (Yii::$app->user->isGuest) {
         NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
        $menuItems = [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Signup', 'url' => ['/site/signup']],
            ['label' => 'Login', 'url' => ['/site/login']],
            ['label' => 'Admin', 'url' => ['/site/admin']],
        ];
    } else {
         NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => 'http://exam.yii/index.php?r=exam%2Findex',
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
        $menuItems = [
            ['label' => 'Home', 'url' => ['/exam/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ];
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->first_name . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>